AlaFortanFoni/Controllers/AdminArticleController.cs
using AlaFortanFoni.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;

namespace AlaFortanFoni.Controllers
{
    //Makale insert, delete, update, create ve bazı işlemleri için Admin Controller açıldı. 
    public class AdminArticleController : Controller
    {
        //Database bağlantımızı yaptık.
        MvcDB db = new MvcDB();


        // GET: AdminArticle // Article(makalelerimizi) ilk on tanesini listeledim
        public ActionResult Index(int Page = 1)
        {
            var articles = db.Article.OrderByDescending(a => a.ArticleId).ToPagedList(Page, 10);
            return View(articles);
        }

        // GET: AdminArticle/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AdminArticle/Create
        public ActionResult Create()
        {
            // Makale eklemek için gerekli registerleri listeledik ve kategori id ye göre kategori isimlerini çağırdık.
            ViewBag.CategoryId = new SelectList(db.Category, "CategoryId", "CategoryName");
            return View();
        }

        // POST: AdminArticle/Create
        [HttpPost]  // Girilen bilgilerin post edilmesi ve kaydedilmesi burada oluşacak.
        public ActionResult Create(Article article, HttpPostedFileBase Photo)
        {
            if (ModelState.IsValid)
            {
                if (Photo != null)
                {
                    WebImage img = new WebImage(Photo.InputStream);
                    FileInfo photoinfo = new FileInfo(Photo.FileName);
                    string newphoto = Guid.NewGuid().ToString() + photoinfo.Extension;
                    img.Resize(800, 350);

                    //Foto eklemek için Uploads Klasörü açıldı ve yolunu verildi. foto kayıtları buraya gelecek database'e de  yolunu gönderildi.
                    img.Save("~/UpLoads/ArticlePhoto/" + newphoto);
                    article.ArticlePhoto = "/UpLoads/ArticlePhoto/" + newphoto;

                    article.UserId = Convert.ToInt32(Session["userid"]); //oturumu açmış admin kişinin makale eklemesi için 
                    db.Article.Add(article);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }


            }
            return View(article);

        }

        // GET: AdminArticle/Edit/5

        public ActionResult Edit(int id)
        {
            //Edit etmek için önce id ye göre makaleyi çekiyoruz.
            var article = db.Article.Where(a => a.ArticleId == id).SingleOrDefault();
            if (article == null)
            {
                return HttpNotFound();
            }

            //Makelenin kategorisini çekiyerouz.
            ViewBag.CategoryId = new SelectList(db.Category, "CategoryId", "CategoryName", article.CategoryId);

            return View(article);
        }

        // POST: AdminArticle/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, HttpPostedFileBase Photo, Article article)
        {
            try
            {
                //güncelleme işlemi için yeni bir değişken (articles) atayıp. bu değişken üzerinden yeni veriler eklenecek
                var articles = db.Article.Where(a => a.ArticleId == id).SingleOrDefault();

                // Fotoğrafın Update yapılması için kod bloğu
                if (Photo != null)
                {
                    if (System.IO.File.Exists(Server.MapPath(articles.ArticlePhoto)))
                    {
                        System.IO.File.Delete(Server.MapPath(articles.ArticlePhoto));
                    }

                    WebImage img = new WebImage(Photo.InputStream);
                    FileInfo photoinfo = new FileInfo(Photo.FileName);
                    string newphoto = Guid.NewGuid().ToString() + photoinfo.Extension;
                    img.Resize(800, 350);

                    img.Save("~/UpLoads/ArticlePhoto/" + newphoto);
                    articles.ArticlePhoto = "/UpLoads/ArticlePhoto/" + newphoto;

                    // eski bilgileri articles değişkenine atadık. (article değişkeninden article(s) değişkenine)
                    articles.Text = article.Text;
                    articles.Title = article.Title;
                    articles.CategoryId = article.CategoryId;
                    db.SaveChanges();

                }
                return RedirectToAction("Index");

            }
            catch
            {

                return View(article);
            }
        }

        // GET: AdminArticle/Delete/5
        public ActionResult Delete(int id)
        {
            var article = db.Article.Where(a => a.ArticleId == id).SingleOrDefault();
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: AdminArticle/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {     //makelemizi id ye göre çağırdık silme işlemini id ye göre yapacağız.
                var article = db.Article.Where(a => a.ArticleId == id).SingleOrDefault();
                if (article == null)
                {
                    return HttpNotFound();
                }

                //Fotoyu siler
                if (System.IO.File.Exists(Server.MapPath(article.ArticlePhoto)))
                {
                    System.IO.File.Delete(Server.MapPath(article.ArticlePhoto));
                }

                // Yapılan yorumları siler 
                foreach (var i in article.Comment.ToList())
                {
                    db.Comment.Remove(i);
                }

                db.Article.Remove(article); 
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

AlaFortanFoni/Views/AdminArticle/Create.cshtml
@model AlaFortanFoni.Models.Article

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout - Admin.cshtml";
}

<h2>New Article</h2>

@using (Html.BeginForm("Create", "AdminArticle", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" }  })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArticlePhoto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               <input type="file" id="Photo" name="Photo" accept=".jpg, .png, .gif, .JPEG, .jpeg" class="form-control" />
                @Html.ValidationMessageFor(model => model.ArticlePhoto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AlaFortanFoni/Views/AdminArticle/Delete.cshtml
@model AlaFortanFoni.Models.Article

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout - Admin.cshtml";
}



<h3>Bu makaleyi Silmek istiyor musunuz?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArticlePhoto)
        </dt>

        <dd>
            <img width="150" src="@Model.ArticlePhoto" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Displayed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Displayed)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" /> |
            @Html.ActionLink("Geri Dön", "Index")
        </div>
    }
</div>

AlaFortanFoni/Views/AdminArticle/Edit.cshtml
@model AlaFortanFoni.Models.Article

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout - Admin.cshtml";
}

<h2>Makale Düzenle</h2>

@using (Html.BeginForm("Edit", "AdminArticle", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ArticleId)

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Befor Photo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img width="75" src="@Model.ArticlePhoto" />
                @Html.ValidationMessageFor(model => model.ArticlePhoto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArticlePhoto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Photo" name="Photo" accept=".jpg, .png, .gif, .JPEG, .jpeg" class="form-control" />
                @Html.ValidationMessageFor(model => model.ArticlePhoto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" , @type = "date" } })
                @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Güncelle" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Geri Dön", "Index")
</div>

AlaFortanFoni/Views/AdminArticle/Index.cshtml
<!-- Makale Listesini sayfalara ayırmak için Paget listi ekledik    -->
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<AlaFortanFoni.Models.Article>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout - Admin.cshtml";
}



<p>
    @Html.ActionLink("Yeni Makale Ekle", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.Label("CategoryName")
        </th>
        <th>
            @Html.Label("Creat User")
        </th>
        <th>
            @Html.Label("Title")
        </th>
       
        <th>
            @Html.Label("ArticlePhoto")
        </th>
        <th>
            @Html.Label("Time")
        </th>
        <th>
            @Html.Label("Displayed")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Category.CategoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
       
        <td>
           <img width="75" src="@item.ArticlePhoto" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Time)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Displayed)
        </td>
        <td>
            @Html.ActionLink("Düzenle", "Edit", new { id=item.ArticleId }) |
            @Html.ActionLink("Detay", "Details", new { id=item.ArticleId }) |
            @Html.ActionLink("Sil", "Delete", new { id=item.ArticleId })
        </td>
    </tr>
}

</table>

<div class="row">
    <div class="col-md-8 text-center">
        <div class="pagedList pagination-lg">
            @Html.PagedListPager(Model, Page => Url.Action("Index", new { Page }), PagedListRenderOptions.Classic)
        </div>
    </div>

</div>